[2024-02-06T03:29:08.335+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: nyctaxi_elt.creating_table manual__2024-02-06T03:29:07.032208+00:00 [queued]>
[2024-02-06T03:29:08.347+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: nyctaxi_elt.creating_table manual__2024-02-06T03:29:07.032208+00:00 [queued]>
[2024-02-06T03:29:08.347+0000] {taskinstance.py:1368} INFO - 
--------------------------------------------------------------------------------
[2024-02-06T03:29:08.348+0000] {taskinstance.py:1369} INFO - Starting attempt 1 of 1
[2024-02-06T03:29:08.348+0000] {taskinstance.py:1370} INFO - 
--------------------------------------------------------------------------------
[2024-02-06T03:29:08.360+0000] {taskinstance.py:1389} INFO - Executing <Task(PostgresOperator): creating_table> on 2024-02-06 03:29:07.032208+00:00
[2024-02-06T03:29:08.366+0000] {standard_task_runner.py:52} INFO - Started process 1109 to run task
[2024-02-06T03:29:08.368+0000] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'nyctaxi_elt', 'creating_table', 'manual__2024-02-06T03:29:07.032208+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/nyctaxi_elt.py', '--cfg-path', '/tmp/tmp0rp48c10', '--error-file', '/tmp/tmp37xuhu9o']
[2024-02-06T03:29:08.369+0000] {standard_task_runner.py:80} INFO - Job 4: Subtask creating_table
[2024-02-06T03:29:08.430+0000] {task_command.py:371} INFO - Running <TaskInstance: nyctaxi_elt.creating_table manual__2024-02-06T03:29:07.032208+00:00 [running]> on host 9d3dd91d9998
[2024-02-06T03:29:08.507+0000] {taskinstance.py:1583} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=nyctaxi_elt
AIRFLOW_CTX_TASK_ID=creating_table
AIRFLOW_CTX_EXECUTION_DATE=2024-02-06T03:29:07.032208+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-02-06T03:29:07.032208+00:00
[2024-02-06T03:29:08.518+0000] {base.py:68} INFO - Using connection ID '***_postgres' for task execution.
[2024-02-06T03:29:08.523+0000] {sql.py:315} INFO - Running statement: CREATE TABLE IF NOT EXISTS nyc_taxi (
                vendorid INT,
                lpep_pickup_datetime TIMESTAMP,
                lpep_dropoff_datetime TIMESTAMP,
                store_and_fwd_flag VARCHAR(1),
                ratecodeid INT,
                pulocationid INT,
                dolocationid INT,
                passenger_count INT,
                trip_distance FLOAT,
                fare_amount FLOAT,
                extra FLOAT,
                mta_tax FLOAT,
                tip_amount FLOAT,
                tolls_amount FLOAT,
                improvement_surcharge FLOAT,
                total_amount FLOAT,
                payment_type INT,
                trip_type INT,
                congestion_surcharge FLOAT
            ), parameters: None
[2024-02-06T03:29:08.524+0000] {postgres.py:94} INFO - NOTICE:  relation "nyc_taxi" already exists, skipping

[2024-02-06T03:29:08.538+0000] {taskinstance.py:1412} INFO - Marking task as SUCCESS. dag_id=nyctaxi_elt, task_id=creating_table, execution_date=20240206T032907, start_date=20240206T032908, end_date=20240206T032908
[2024-02-06T03:29:08.580+0000] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-02-06T03:29:08.611+0000] {local_task_job.py:279} INFO - 0 downstream tasks scheduled from follow-on schedule check
